/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f18f4451-616c-4a85-b75b-e729dbee38ed",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_v4YocZFgz",
    "aws_user_pools_web_client_id": "3egsorm7d2ciu0mb32d1k1ts5p",
    "oauth": {}
};


export default awsmobile;
